/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SOSPatientWorkArea;

import Business.BodyAndSymptom.BodyApparatus;
import Business.BodyAndSymptom.BodyPart;
import Business.BodyAndSymptom.Symptom;
import Business.EcoSystem;
import Business.Role.PatientRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SOSRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author chenxinyun
 */
public class SOSJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SOSJPanel
     */
    private JPanel container;
    private EcoSystem system;

    public SOSJPanel() {

    }

    public SOSJPanel(JPanel container, EcoSystem system) {
        initComponents();
        this.container = container;
        this.system = system;
        populateBodyParts();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        symptom = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bodyPartsList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        bodyApparatusList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        bodySymptom = new javax.swing.JList<>();
        contact = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        streetTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        zipcodeTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        sosButton = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();

        jLabel1.setText("SOS");

        jLabel3.setText("body apparatus:");

        jLabel4.setText("symptom:");

        jLabel5.setText("body parts：");

        bodyPartsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bodyPartsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bodyPartsList);

        bodyApparatusList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bodyApparatusListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(bodyApparatusList);

        jScrollPane3.setViewportView(bodySymptom);

        javax.swing.GroupLayout symptomLayout = new javax.swing.GroupLayout(symptom);
        symptom.setLayout(symptomLayout);
        symptomLayout.setHorizontalGroup(
            symptomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(symptomLayout.createSequentialGroup()
                .addGroup(symptomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(symptomLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel5))
                    .addGroup(symptomLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(symptomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(symptomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        symptomLayout.setVerticalGroup(
            symptomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(symptomLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(symptomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(symptomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Symptom select", symptom);

        jLabel6.setText("Street Address:");

        streetTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("City:");

        jLabel8.setText("Zip Code:");

        jLabel9.setText("Phone:");

        jLabel10.setText("Name:");

        sosButton.setForeground(new java.awt.Color(255, 0, 0));
        sosButton.setText("SOS");
        sosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sosButtonActionPerformed(evt);
            }
        });

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("宋体", 3, 12)); // NOI18N
        jLabel12.setText("An account will be created. Username and password will be your name.");

        javax.swing.GroupLayout contactLayout = new javax.swing.GroupLayout(contact);
        contact.setLayout(contactLayout);
        contactLayout.setHorizontalGroup(
            contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactLayout.createSequentialGroup()
                .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contactLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(nameTextField))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(contactLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zipcodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(streetTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contactLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contactLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap(94, Short.MAX_VALUE))
                    .addGroup(contactLayout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sosButton)
                        .addGap(144, 144, 144))))
        );
        contactLayout.setVerticalGroup(
            contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contactLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(streetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(13, 13, 13)
                .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(7, 7, 7)
                .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(29, 29, 29)
                .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sosButton)
                    .addComponent(backBtn))
                .addGap(63, 63, 63))
        );

        jTabbedPane1.addTab("Contact Information", contact);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setText("EMS Conducting Service");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public void populateBodyParts() {
        DefaultListModel listModel = new DefaultListModel();
        for (BodyPart bp : system.getBodyPartList()) {
            listModel.addElement(bp);
        }
        bodyPartsList.setModel(listModel);

    }

    public void populateBodyApparatus(BodyPart bodyPartSelected) {
        DefaultListModel listModel2 = new DefaultListModel();
        for (BodyApparatus ba : bodyPartSelected.getBodyapparatus()) {
            listModel2.addElement(ba);
        }
        bodyApparatusList.setModel(listModel2);
    }

    public void populateSymptom() {
        BodyApparatus bodyApparatusSelected = (BodyApparatus) bodyApparatusList.getSelectedValue();
        DefaultListModel listModel3 = new DefaultListModel();
        for (Symptom s : bodyApparatusSelected.getSymptomList()) {
            listModel3.addElement(s);
        }

        bodySymptom.setModel(listModel3);
    }

    private void sosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sosButtonActionPerformed
        // TODO add your handling code here:
        SOSRequest sOSRequest = new SOSRequest();
        if (streetTextField.getText().equals("")) {
            return;
        }
        String address = streetTextField.getText();

        if (zipcodeTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter zipcode.");
            return;
        }
        String zipcode = zipcodeTextField.getText();

        if (cityTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter city.");
            return;
        }
        String city = cityTextField.getText();

        if (nameTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter name.");
            return;
        }
        String name = nameTextField.getText();

        if (phoneTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter phone number.");
        }
        String phone = phoneTextField.getText();

        String bodyParts = bodyPartsList.getSelectedValue().toString();
        if (bodyParts == null) {
            JOptionPane.showMessageDialog(null, "Please enter body part.");
            return;
        }
        String bodyapparatus = bodyApparatusList.getSelectedValue().toString();
        if (bodyapparatus == null) {
            JOptionPane.showMessageDialog(null, "Please enter body apparatus.");
            return;
        }
        String symptom = bodySymptom.getSelectedValue().toString();
        if (symptom == null) {
            JOptionPane.showMessageDialog(null, "Please enter symptom.");
            return;
        }

        sOSRequest.setRequestDate(new Date());
        sOSRequest.setBodyPart(bodyParts);
        sOSRequest.setCity(city);
        sOSRequest.setBodyApparatus(bodyapparatus);
        sOSRequest.setName(name);
        sOSRequest.setphone(phone);
        sOSRequest.setStreetAddress(address);
        sOSRequest.setSymptom(symptom);
        sOSRequest.setRequestDate(new Date());
        try {
            sOSRequest.setZipcode(zipcode);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid number");
        }
        UserAccount account = new UserAccount();
        account.setRole(new PatientRole());
        account.setUsername(name);
        account.setPassword(name);
        system.getUserAccountDirectory().getUserAccountList().add(account);
        sOSRequest.setSender(account);

        sOSRequest.setSender(account);
        sOSRequest.setStatus("Forward to EMS");

        system.getWorkQueue().getWorkRequestList().add(sOSRequest);
        SOSProcessViewJPanel sospvjp = new SOSProcessViewJPanel(container, system, account);
        container.add("SOSProcessViewJPanel", sospvjp);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);

    }//GEN-LAST:event_sosButtonActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed

    private void streetTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetTextFieldActionPerformed

    private void bodyPartsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bodyPartsListMouseClicked
        // TODO add your handling code here:
        BodyPart bodyPartSelected = (BodyPart) bodyPartsList.getSelectedValue();
        if (bodyPartSelected != null) {
            populateBodyApparatus(bodyPartSelected);
        }
    }//GEN-LAST:event_bodyPartsListMouseClicked

    private void bodyApparatusListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bodyApparatusListMouseClicked
        BodyApparatus bodyApparatusSelected = (BodyApparatus) bodyApparatusList.getSelectedValue();
        if (bodyApparatusSelected != null) {
            populateSymptom();
        }
    }//GEN-LAST:event_bodyApparatusListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JList bodyApparatusList;
    private javax.swing.JList bodyPartsList;
    private javax.swing.JList<Symptom> bodySymptom;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JPanel contact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JButton sosButton;
    private javax.swing.JTextField streetTextField;
    private javax.swing.JPanel symptom;
    private javax.swing.JTextField zipcodeTextField;
    // End of variables declaration//GEN-END:variables
}
