package Business;

import Business.BodyAndSymptom.BodyApparatus;
import Business.BodyAndSymptom.BodyPart;
import Business.BodyAndSymptom.Symptom;
import Business.DiseaseAndTherapy.Medicine;
import Business.Employee.Employee;
import Business.Organization.Organization;
import Business.Role.AdminRole;
import Business.Role.Role;
import Business.Role.SystemAdminRole;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;

/**
 *
 * @author chenxinyun
 */
public class ConfigureASystem {

    public static EcoSystem configure() {

        EcoSystem system = EcoSystem.getInstance();

        //Create a network
        //create an enterprise
        //initialize some organizations
        //have some employees 
        //create user account
        Employee employee = system.getEmployeeDirectory().createEmployee("Sissi");

        UserAccount ua = system.getUserAccountDirectory().createUserAccount("sysadmin", "sysadmin", employee, new SystemAdminRole());

//hard coding head bodypart
        BodyPart head = system.addBodyPart("head");
        BodyApparatus eye = head.addApparatuses("eye");
        Symptom redBloodEye = eye.addSymptom("red blood eye");
        redBloodEye.getTherapy().setFirstAidMethods("Take Oral antihistamines or anti-hyperemic agents");
        redBloodEye.getTherapy().setSelfcareMethods("If the eye is itchy, cold compress;Remove the contact lens;Do not rub your eyes");
        redBloodEye.getTherapy().setAuxiliaryExamination("Skin test;Blood Test");
        Symptom visualAcuity = eye.addSymptom("visual acuity");
        visualAcuity.getTherapy().setFirstAidMethods("Insulin treatment");
        visualAcuity.getTherapy().setSelfcareMethods("Exercise and eat healthy food");
        visualAcuity.getTherapy().setAuxiliaryExamination("Physical examination;Measure blood glucose and HbA1c levels");
        Symptom eyePainOrDiscomfort = eye.addSymptom("pain or discomfort");
        eyePainOrDiscomfort.getTherapy().setFirstAidMethods("Eye drops;Face ice pack");
        eyePainOrDiscomfort.getTherapy().setSelfcareMethods("Rinse with running water for 20 minutes");
        eyePainOrDiscomfort.getTherapy().setAuxiliaryExamination("Eye examination with blue lights");
        Symptom ghosting = eye.addSymptom("ghosting");
        ghosting.getTherapy().setFirstAidMethods("Surgery to remove turbid crystals while implanted intraocular lens");
        ghosting.getTherapy().setSelfcareMethods("Wear sunglasses or broad-brimmed hat");
        ghosting.getTherapy().setAuxiliaryExamination("Comprehensive eye examination");
        Symptom eyeSwelling = eye.addSymptom("swelling");
        eyeSwelling.getTherapy().setFirstAidMethods("Antibiotic ointment or eye drops");
        eyeSwelling.getTherapy().setSelfcareMethods("Hot or cold eyes 3-4 times a day;Wipe the crust with gauze or cotton wool soaked in warm water");
        eyeSwelling.getTherapy().setAuxiliaryExamination("Physical examination;Eye secretions test");
        Symptom eyeNystagmus = eye.addSymptom("nystagmus");
        eyeNystagmus.getTherapy().setFirstAidMethods("Thiamine");
        eyeNystagmus.getTherapy().setSelfcareMethods("Prohibition of alcohol");
        eyeNystagmus.getTherapy().setAuxiliaryExamination("Blood test;Urinalysis;Brain CT");
        Symptom eyecramps = eye.addSymptom("cramps");
        eyecramps.getTherapy().setFirstAidMethods("Antihistamines;Antiviral medicine;Antibiotic");
        eyecramps.getTherapy().setSelfcareMethods("Lying still;Drink more water");
        eyecramps.getTherapy().setAuxiliaryExamination("Hearing test;Exercise test;CT Scan;");
        Symptom blindness = eye.addSymptom("blindness");
        blindness.getTherapy().setFirstAidMethods("Retina current graph;Refractive inspection");
        blindness.getTherapy().setSelfcareMethods("Wait for surgery");
        blindness.getTherapy().setAuxiliaryExamination("Fluorescein angiography;Ultrasonography");

        BodyApparatus ear = head.addApparatuses("ear");
        Symptom tinnitus = ear.addSymptom("tinnitus");
        tinnitus.getTherapy().setFirstAidMethods("Remove excess earwax;Antidepressants");
        tinnitus.getTherapy().setSelfcareMethods("Use hearing aid");
        tinnitus.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom itching = ear.addSymptom("itching");
        itching.getTherapy().setFirstAidMethods("Rinse with warm water and drops");
        itching.getTherapy().setSelfcareMethods("Clean the ears");
        itching.getTherapy().setAuxiliaryExamination("Endoscopy view");
        Symptom earmass = ear.addSymptom("mass or bulge");
        earmass.getTherapy().setFirstAidMethods("Extract the excess blood from your ears");
        earmass.getTherapy().setSelfcareMethods("Cold pack with ice bag；Wear protective headgear");
        earmass.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom earbleeding = ear.addSymptom("bleeding");
        earbleeding.getTherapy().setFirstAidMethods("Extract the excess blood from your ears；Pressure with a bandage to prevent edema");
        earbleeding.getTherapy().setSelfcareMethods("Cold pack with ice bag；Wear protective headgear");
        earbleeding.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom earswelling = ear.addSymptom("swelling");
        earswelling.getTherapy().setFirstAidMethods("Pressure with a bandage to prevent edema；antibiotic");
        earswelling.getTherapy().setSelfcareMethods("Cold pack with ice bag");
        earswelling.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom earbruising = ear.addSymptom("bruising discoloration");
        earbruising.getTherapy().setFirstAidMethods("OTC pain killers；Hot compress");
        earbruising.getTherapy().setSelfcareMethods("Hold up the bruised parts");
        earbruising.getTherapy().setAuxiliaryExamination("x-ray;blood test");
        Symptom eardrain = ear.addSymptom("drain or pus");
        eardrain.getTherapy().setFirstAidMethods("OTC pain killers;antibiotic");
        eardrain.getTherapy().setSelfcareMethods("Keep the tympanic membrane dry");
        eardrain.getTherapy().setAuxiliaryExamination("Otoscope examination；Hearing test");
        Symptom earnumbness = ear.addSymptom("numbness");
        earnumbness.getTherapy().setFirstAidMethods("Remove blisters or necrotic tissue；Intravenous and intravenous electrolytes");
        earnumbness.getTherapy().setSelfcareMethods("Lift up to the area above the heart；Dip in cold water for 15 minutes");
        earnumbness.getTherapy().setAuxiliaryExamination("Physical examination");

        BodyApparatus face = head.addApparatuses("face");
        Symptom facemass = face.addSymptom("mass or bulge");
        facemass.getTherapy().setFirstAidMethods("Cut the abscess；Antibiotic ointment");
        facemass.getTherapy().setSelfcareMethods("Heat 4 times a day, every 30 minutes");
        facemass.getTherapy().setAuxiliaryExamination("Wound tissue fluid culture；blood test；Film degree exam");
        Symptom facedrooping = face.addSymptom("side drooping");
        facedrooping.getTherapy().setFirstAidMethods("Steroid drugs；Antiviral medicine");
        facedrooping.getTherapy().setSelfcareMethods("Eye drops, artificial tears；Hot compress；Relaxation exercise and deep breathing");
        facedrooping.getTherapy().setAuxiliaryExamination("blood test；EMG；CT Scan;");
        Symptom facetenderness = face.addSymptom("tenderness");
        facetenderness.getTherapy().setFirstAidMethods("Sinus drainage");
        facetenderness.getTherapy().setSelfcareMethods("Use nasal syringe or nasal pot filled with sterile warm saline irrigation sinus");
        facetenderness.getTherapy().setAuxiliaryExamination("CT Scan;X-ray;MRIs");
        Symptom facedeformity = face.addSymptom("visible deformity");
        facedeformity.getTherapy().setFirstAidMethods("OTC pain killers；Hold down the bleeding site");
        facedeformity.getTherapy().setSelfcareMethods("Apply with ice bag");
        facedeformity.getTherapy().setAuxiliaryExamination("Eye examination;CT Scan ");
        Symptom facefever = face.addSymptom("fever");
        facefever.getTherapy().setFirstAidMethods("Cut the abscess");
        facefever.getTherapy().setSelfcareMethods("Use antibacterial soap to clean");
        facefever.getTherapy().setAuxiliaryExamination("Check the abscess and its surrounding tissue；Wound tissue fluid culture");
        Symptom facedrain = face.addSymptom("drain or pus");
        facedrain.getTherapy().setFirstAidMethods("Adrenaline injection；Oxygen；Intravenous infusion");
        facedrain.getTherapy().setSelfcareMethods("Take Antihistamines;`Ice allergy site");
        facedrain.getTherapy().setAuxiliaryExamination("blood test；Allergen detection");
        Symptom facebruising = face.addSymptom("bruising discoloration");
        facebruising.getTherapy().setFirstAidMethods("OTC pain killers");
        facebruising.getTherapy().setSelfcareMethods("Ice 10-20 minutes");
        facebruising.getTherapy().setAuxiliaryExamination("x-ray;blood test");
        Symptom facetwitching = face.addSymptom("muscle twitching");
        facetwitching.getTherapy().setFirstAidMethods("Anticonvulsant drugs；Deliver Short-pulse electrical energy to the brain through the large nerves of the neck");
        facetwitching.getTherapy().setSelfcareMethods("Turn aside to allow any liquid in your mouth to flow out");
        facetwitching.getTherapy().setAuxiliaryExamination("Intensity and reflex testing；EEG test；MRI;CT Scan");
        Symptom faceswollen = face.addSymptom("glands larger or swollen");
        faceswollen.getTherapy().setFirstAidMethods("Warm saline mouthwash");
        faceswollen.getTherapy().setSelfcareMethods("Drink plenty of water");
        faceswollen.getTherapy().setAuxiliaryExamination("Buccal swabs；Blood Test");

        BodyApparatus nose = head.addApparatuses("nose");
        Symptom nosebleeds = nose.addSymptom("nosebleeds");
        nosebleeds.getTherapy().setFirstAidMethods("OTC antihistamines;Steroid nasal spray");
        nosebleeds.getTherapy().setSelfcareMethods("Use vaseline or antibiotic ointment or saline nasal spray");
        nosebleeds.getTherapy().setAuxiliaryExamination("Skin test");
        Symptom nasal = nose.addSymptom("nasal breathing difficulties");
        nasal.getTherapy().setFirstAidMethods("OTC antihistamines;Steroid nasal spray");
        nasal.getTherapy().setSelfcareMethods("Clean the sinuses with warm saline");
        nasal.getTherapy().setAuxiliaryExamination("Skin test");
        Symptom nosedrain = nose.addSymptom("drain or pus");
        nosedrain.getTherapy().setFirstAidMethods("Sinus drainage；Bromelain");
        nosedrain.getTherapy().setSelfcareMethods("Use vaseline or antibiotic ointment or saline nasal spray");
        nosedrain.getTherapy().setAuxiliaryExamination("MRI;CT Scan；X-ray");
        Symptom nosemass = nose.addSymptom("mass or bulge");
        nosemass.getTherapy().setFirstAidMethods("Cut the abscess");
        nosemass.getTherapy().setSelfcareMethods("Use antibacterial soap to clean");
        nosemass.getTherapy().setAuxiliaryExamination("Check the abscess and its surrounding tissue；Wound tissue fluid culture");
        Symptom nosedeformity = nose.addSymptom("visible deformity");
        nosedeformity.getTherapy().setFirstAidMethods("Reset the nasal bone");
        nosedeformity.getTherapy().setSelfcareMethods("Use nose tip decongestant");
        nosedeformity.getTherapy().setAuxiliaryExamination("X-ray;CT Scan");
        Symptom nosetingling = nose.addSymptom("tingling");
        nosetingling.getTherapy().setFirstAidMethods("Remove blisters or necrotic tissue");
        nosetingling.getTherapy().setSelfcareMethods("Dip in cold water for 15 minutes");
        nosetingling.getTherapy().setAuxiliaryExamination("Full physical examination");
        Symptom nosediscoloration = nose.addSymptom("bruising discoloration");
        nosediscoloration.getTherapy().setFirstAidMethods("OTC antihistamines");
        nosediscoloration.getTherapy().setSelfcareMethods("Ice compress for 20-30 minutes");
        nosediscoloration.getTherapy().setAuxiliaryExamination("x-ray;blood test");
        Symptom breathing = nose.addSymptom("breathing noise");
        breathing.getTherapy().setFirstAidMethods("Decongestant；Antihistamines；Corticosteroid spray");
        breathing.getTherapy().setSelfcareMethods("Drink lots of hot drinks；Nasal spray to clean");
        breathing.getTherapy().setAuxiliaryExamination("Throat swabs culture；Allergy test；blood test");

        BodyApparatus mouth = head.addApparatuses("mouth");
        Symptom breath = mouth.addSymptom("bad breath");
        breath.getTherapy().setFirstAidMethods("Remove dental plaque on the teeth");
        breath.getTherapy().setSelfcareMethods("Brushing teeth");
        breath.getTherapy().setAuxiliaryExamination("Check the depth of the periodontal pocket for each tooth");
        Symptom bleeding = mouth.addSymptom("bleeding gums");
        bleeding.getTherapy().setFirstAidMethods("Intravenous infusion or injection of clotting factor");
        bleeding.getTherapy().setSelfcareMethods("Avoid contact with alcohol");
        bleeding.getTherapy().setAuxiliaryExamination("blood test");
        Symptom sore = mouth.addSymptom("sore tongue");
        sore.getTherapy().setFirstAidMethods("Blood transfusion；Folic acid supplements");
        sore.getTherapy().setSelfcareMethods("Do not take iron supplements");
        sore.getTherapy().setAuxiliaryExamination("blood test");
        Symptom cough = mouth.addSymptom("cough");
        cough.getTherapy().setFirstAidMethods("Cough medicine and expectorant medicine");
        cough.getTherapy().setSelfcareMethods("OTC pain killers");
        cough.getTherapy().setAuxiliaryExamination("Lung examination；Chest x-ray");
        Symptom saliva = mouth.addSymptom("saliva or mucus");
        saliva.getTherapy().setFirstAidMethods("Dilute mucus；Bronchodilator");
        saliva.getTherapy().setSelfcareMethods("Phlegm medicine；Drink plenty of water");
        saliva.getTherapy().setAuxiliaryExamination("blood test；Pulmonary function test；CT Scan;x-ray");
        Symptom gum = mouth.addSymptom("gum ulcer");
        gum.getTherapy().setFirstAidMethods("Silver nitrate；Folic acid");
        gum.getTherapy().setSelfcareMethods("Hydrogen peroxide water disinfection；Apply a small amount of milky magnesia");
        gum.getTherapy().setAuxiliaryExamination("Check the ulcer itself");
        Symptom hiccups = mouth.addSymptom("hiccups");
        hiccups.getTherapy().setFirstAidMethods("Antacids");
        hiccups.getTherapy().setSelfcareMethods("Raise the bed 10-15 cm");
        hiccups.getTherapy().setAuxiliaryExamination("Endoscope to see the stomach；blood test");

        BodyApparatus neck = head.addApparatuses("neck");
        Symptom stiff = neck.addSymptom("stiff or difficult to move");
        stiff.getTherapy().setFirstAidMethods("Fibromyalgia medication");
        stiff.getTherapy().setSelfcareMethods("put heated pads on sore muscles");
        stiff.getTherapy().setAuxiliaryExamination("blood test；x-ray");
        Symptom unconscious = neck.addSymptom("unconscious rotation");
        unconscious.getTherapy().setFirstAidMethods("Muscle relaxation medicine；Deep brain stimulation");
        unconscious.getTherapy().setSelfcareMethods("Hot compress；pain killers");
        unconscious.getTherapy().setAuxiliaryExamination("x-ray；Magnetic resonance imaging；CT scan");
        Symptom neckcramps = neck.addSymptom("muscle cramps");
        neckcramps.getTherapy().setFirstAidMethods("Non-steroidal anti-inflammatory drugs");
        neckcramps.getTherapy().setSelfcareMethods("Ice compress");
        neckcramps.getTherapy().setAuxiliaryExamination("blood test；x-ray");
        Symptom numbness = neck.addSymptom("numbness");
        numbness.getTherapy().setFirstAidMethods("Inject tetanus vaccine");
        numbness.getTherapy().setSelfcareMethods("Clear chemicals on the skin；Rinse with cold water for 15-20 minutes");
        numbness.getTherapy().setAuxiliaryExamination("blood test；CT Scan;x-ray");
        Symptom pus = neck.addSymptom("drain or pus");
        pus.getTherapy().setFirstAidMethods("Adrenaline injection；Corticosteroid drugs；Oxygen；Intravenous infusion");
        pus.getTherapy().setSelfcareMethods("Antihistamines；Ice allergy site");
        pus.getTherapy().setAuxiliaryExamination("blood test；Allergen test");
        Symptom joint = neck.addSymptom("joint pain");
        joint.getTherapy().setFirstAidMethods("DMARD;Inhibit the immune system drugs；Biological agents");
        joint.getTherapy().setSelfcareMethods("Anti-inflammatory drugs；Cold compress");
        joint.getTherapy().setAuxiliaryExamination("Physical examination；Blood Test;x-ray");
        Symptom visible = neck.addSymptom("visible deformity");
        visible.getTherapy().setFirstAidMethods("Reset the nasal bone");
        visible.getTherapy().setSelfcareMethods("Use nose tip decongestant");
        visible.getTherapy().setAuxiliaryExamination("X-ray;CT Scan");
        Symptom neckbleeding = neck.addSymptom("bleeding");
        neckbleeding.getTherapy().setFirstAidMethods("Extract the excess blood from your ears；Pressure with a bandage to prevent edema");
        neckbleeding.getTherapy().setSelfcareMethods("Cold pack with ice bag；Wear protective headgear");
        neckbleeding.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom neckfever = neck.addSymptom("fever");
        neckfever.getTherapy().setFirstAidMethods("Cut the abscess");
        neckfever.getTherapy().setSelfcareMethods("Use antibacterial soap to clean");
        neckfever.getTherapy().setAuxiliaryExamination("Check the abscess and its surrounding tissue；Wound tissue fluid culture");

        // chest body part
        BodyPart chest = system.addBodyPart("chest");
        BodyApparatus frontChest = chest.addApparatuses("front chest");
        Symptom frontChestpain = frontChest.addSymptom("pain or discomfort");
        frontChestpain.getTherapy().setFirstAidMethods("Anti-inflammatory drugs；Cortisol injection");
        frontChestpain.getTherapy().setSelfcareMethods("Hot compress");
        frontChestpain.getTherapy().setAuxiliaryExamination("x-ray；Magnetic resonance imaging；CT scan");
        Symptom chestpressure = frontChest.addSymptom("pressure or heavy feeling");
        chestpressure.getTherapy().setFirstAidMethods("OTC antacids");
        chestpressure.getTherapy().setSelfcareMethods("Drink plenty of water");
        chestpressure.getTherapy().setAuxiliaryExamination("Endoscopy");
        Symptom frontChesttenderness = frontChest.addSymptom("tenderness");
        frontChesttenderness.getTherapy().setFirstAidMethods("Fibromyalgia medication；massage；Stretch regularly；Acupuncture");
        frontChesttenderness.getTherapy().setSelfcareMethods("Use heat pads on sore muscles");
        frontChesttenderness.getTherapy().setAuxiliaryExamination("x-ray；Magnetic resonance imaging；CT scan");
        Symptom heartbeat = frontChest.addSymptom("irregular heartbeat");
        heartbeat.getTherapy().setFirstAidMethods("Anti-arrhythmic drugs；pacemaker；Ablation treatment");
        heartbeat.getTherapy().setSelfcareMethods("Avoid drugs that contain stimulants");
        heartbeat.getTherapy().setAuxiliaryExamination("Electrocardiogram；Echocardiography；MRI");
        Symptom frontChestnumbness = frontChest.addSymptom("numbness");
        frontChestnumbness.getTherapy().setFirstAidMethods("Inject tetanus vaccine");
        frontChestnumbness.getTherapy().setSelfcareMethods("Clear chemicals on the skin；Rinse with cold water for 15-20 minutes");
        frontChestnumbness.getTherapy().setAuxiliaryExamination("blood test；CT Scan;x-ray");
        Symptom frontChestmass = frontChest.addSymptom("mass or bulge");
        frontChestmass.getTherapy().setFirstAidMethods("Cut the abscess");
        frontChestmass.getTherapy().setSelfcareMethods("Use antibacterial soap to clean");
        frontChestmass.getTherapy().setAuxiliaryExamination("Check the abscess and its surrounding tissue；Wound tissue fluid culture");
        Symptom frontChestfracture = frontChest.addSymptom("fracture");
        frontChestfracture.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        frontChestfracture.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        frontChestfracture.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");
        Symptom frontChestbleeding = frontChest.addSymptom("bleeding");
        frontChestbleeding.getTherapy().setFirstAidMethods("Extract the excess blood from your ears；Pressure with a bandage to prevent edema");
        frontChestbleeding.getTherapy().setSelfcareMethods("Cold pack with ice bag；Wear protective headgear");
        frontChestbleeding.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");

        BodyApparatus armpit = chest.addApparatuses("armpit");
        Symptom armpittenderness = armpit.addSymptom("gland tenderness");
        armpittenderness.getTherapy().setFirstAidMethods("Fibromyalgia medication；massage；Stretch regularly；Acupuncture");
        armpittenderness.getTherapy().setSelfcareMethods("Use heat pads on sore muscles");
        armpittenderness.getTherapy().setAuxiliaryExamination("x-ray；Magnetic resonance imaging；CT scan");
        Symptom armpitpain = armpit.addSymptom("pain or discomfort");
        armpitpain.getTherapy().setFirstAidMethods("Anti-inflammatory drugs；Cortisol injection");
        armpitpain.getTherapy().setSelfcareMethods("Hot compress");
        armpitpain.getTherapy().setAuxiliaryExamination("x-ray；Magnetic resonance imaging；CT scan");
        Symptom armpitmass = armpit.addSymptom("mass or bulge");
        armpitmass.getTherapy().setFirstAidMethods("Cut the abscess");
        armpitmass.getTherapy().setSelfcareMethods("Use antibacterial soap to clean");
        armpitmass.getTherapy().setAuxiliaryExamination("Check the abscess and its surrounding tissue；Wound tissue fluid culture");
        Symptom chestpain = armpit.addSymptom("excessive sweating");
        Symptom armpitbleeding = armpit.addSymptom("bleeding");
        armpitbleeding.getTherapy().setFirstAidMethods("Extract the excess blood from your ears；Pressure with a bandage to prevent edema");
        armpitbleeding.getTherapy().setSelfcareMethods("Cold pack with ice bag；Wear protective headgear");
        armpitbleeding.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom armpitswelling = armpit.addSymptom("swelling");
        armpitswelling.getTherapy().setFirstAidMethods("Pressure with a bandage to prevent edema；antibiotic");
        armpitswelling.getTherapy().setSelfcareMethods("Cold pack with ice bag");
        armpitswelling.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom armpitbruising = armpit.addSymptom("bruising discoloration");
        armpitbruising.getTherapy().setFirstAidMethods("OTC pain killers；Hot compress");
        armpitbruising.getTherapy().setSelfcareMethods("Hold up the bruised parts");
        armpitbruising.getTherapy().setAuxiliaryExamination("x-ray;blood test");

        BodyApparatus sideChest = chest.addApparatuses("sideChest");
        Symptom sideChestpain = sideChest.addSymptom("pain or discomfort");
        sideChestpain.getTherapy().setFirstAidMethods("Anti-inflammatory drugs；Cortisol injection");
        sideChestpain.getTherapy().setSelfcareMethods("Hot compress");
        sideChestpain.getTherapy().setAuxiliaryExamination("x-ray；Magnetic resonance imaging；CT scan");
        Symptom sideChestdeformity = sideChest.addSymptom("visible deformity");
        sideChestdeformity.getTherapy().setFirstAidMethods("Reset the nasal bone");
        sideChestdeformity.getTherapy().setSelfcareMethods("Use nose tip decongestant");
        sideChestdeformity.getTherapy().setAuxiliaryExamination("X-ray;CT Scan");
        Symptom sideChestbruising = sideChest.addSymptom("bruising discoloration");
        sideChestbruising.getTherapy().setFirstAidMethods("OTC pain killers；Hot compress");
        sideChestbruising.getTherapy().setSelfcareMethods("Hold up the bruised parts");
        sideChestbruising.getTherapy().setAuxiliaryExamination("x-ray;blood test");
        Symptom sideChestmass = sideChest.addSymptom("mass or bulge");
        sideChestmass.getTherapy().setFirstAidMethods("Cut the abscess");
        sideChestmass.getTherapy().setSelfcareMethods("Use antibacterial soap to clean");
        sideChestmass.getTherapy().setAuxiliaryExamination("Check the abscess and its surrounding tissue；Wound tissue fluid culture");
        Symptom sideChestpus = sideChest.addSymptom("drain or pus");
        sideChestpus.getTherapy().setFirstAidMethods("Adrenaline injection；Corticosteroid drugs；Oxygen；Intravenous infusion");
        sideChestpus.getTherapy().setSelfcareMethods("Antihistamines；Ice allergy site");
        sideChestpus.getTherapy().setAuxiliaryExamination("blood test；Allergen test");
        Symptom sideChestbleeding = sideChest.addSymptom("bleeding");
        sideChestbleeding.getTherapy().setFirstAidMethods("Extract the excess blood from your ears；Pressure with a bandage to prevent edema");
        sideChestbleeding.getTherapy().setSelfcareMethods("Cold pack with ice bag；Wear protective headgear");
        sideChestbleeding.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");

        //abdomen body part
        BodyPart abdomen = system.addBodyPart("abdomen");
        BodyApparatus upperAbdomen = abdomen.addApparatuses("upperAbdomen");
        Symptom upperAbdomenpain = upperAbdomen.addSymptom("pain or discomfort");
        upperAbdomenpain.getTherapy().setFirstAidMethods("Anti-inflammatory drugs；Cortisol injection");
        upperAbdomenpain.getTherapy().setSelfcareMethods("Hot compress");
        upperAbdomenpain.getTherapy().setAuxiliaryExamination("x-ray；Magnetic resonance imaging；CT scan");
        Symptom upperAbdomencramps = upperAbdomen.addSymptom("muscle cramps");
        upperAbdomencramps.getTherapy().setFirstAidMethods("Interferon；Corticosteroids");
        upperAbdomencramps.getTherapy().setSelfcareMethods("Take a deep breath or meditate；Use brace, crutches");
        upperAbdomencramps.getTherapy().setAuxiliaryExamination("Neurological examination；Nuclear magnetic resonance；Spinal cord puncture");
        Symptom upperAbdomenmass = upperAbdomen.addSymptom("mass or bulge");
        upperAbdomenmass.getTherapy().setFirstAidMethods("Cut the abscess");
        upperAbdomenmass.getTherapy().setSelfcareMethods("Use antibacterial soap to clean");
        upperAbdomenmass.getTherapy().setAuxiliaryExamination("Check the abscess and its surrounding tissue；Wound tissue fluid culture");
        Symptom upperAbdomenpus = upperAbdomen.addSymptom("drain or pus");
        upperAbdomenpus.getTherapy().setFirstAidMethods("Adrenaline injection；Corticosteroid drugs；Oxygen；Intravenous infusion");
        upperAbdomenpus.getTherapy().setSelfcareMethods("Antihistamines；Ice allergy site");
        upperAbdomenpus.getTherapy().setAuxiliaryExamination("blood test；Allergen test");
        Symptom upperAbdomendeformity = upperAbdomen.addSymptom("visible deformity");
        upperAbdomendeformity.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        upperAbdomendeformity.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        upperAbdomendeformity.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");
        Symptom upperAbdomenswelling = upperAbdomen.addSymptom("swelling");
        upperAbdomenswelling.getTherapy().setFirstAidMethods("Pressure with a bandage to prevent edema；antibiotic");
        upperAbdomenswelling.getTherapy().setSelfcareMethods("Cold pack with ice bag");
        upperAbdomenswelling.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom upperAbdomenbleeding = upperAbdomen.addSymptom("bleeding");
        upperAbdomenbleeding.getTherapy().setFirstAidMethods("Extract the excess blood from your ears；Pressure with a bandage to prevent edema");
        upperAbdomenbleeding.getTherapy().setSelfcareMethods("Cold pack with ice bag；Wear protective headgear");
        upperAbdomenbleeding.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");

        BodyApparatus lowerAbdomen = abdomen.addApparatuses("lowerAbdomen");
        Symptom lowerAbdomenpain = lowerAbdomen.addSymptom("pain or discomfort");
        lowerAbdomenpain.getTherapy().setFirstAidMethods("Anti-inflammatory drugs；Cortisol injection");
        lowerAbdomenpain.getTherapy().setSelfcareMethods("Hot compress");
        lowerAbdomenpain.getTherapy().setAuxiliaryExamination("x-ray；Magnetic resonance imaging；CT scan");
        Symptom lowerAbdomenswelling = lowerAbdomen.addSymptom("swelling");
        lowerAbdomenswelling.getTherapy().setFirstAidMethods("Pressure with a bandage to prevent edema；antibiotic");
        lowerAbdomenswelling.getTherapy().setSelfcareMethods("Cold pack with ice bag");
        lowerAbdomenswelling.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom lowerAbdomenpus = lowerAbdomen.addSymptom("drain or pus");
        lowerAbdomenpus.getTherapy().setFirstAidMethods("Adrenaline injection；Corticosteroid drugs；Oxygen；Intravenous infusion");
        lowerAbdomenpus.getTherapy().setSelfcareMethods("Antihistamines；Ice allergy site");
        lowerAbdomenpus.getTherapy().setAuxiliaryExamination("blood test；Allergen test");
        Symptom lowerAbdomenmass = lowerAbdomen.addSymptom("mass or bulge");
        lowerAbdomenmass.getTherapy().setFirstAidMethods("Cut the abscess");
        lowerAbdomenmass.getTherapy().setSelfcareMethods("Use antibacterial soap to clean");
        lowerAbdomenmass.getTherapy().setAuxiliaryExamination("Check the abscess and its surrounding tissue；Wound tissue fluid culture");
        Symptom lowerAbdomenbruising = lowerAbdomen.addSymptom("bruising discoloration");
        lowerAbdomenbruising.getTherapy().setFirstAidMethods("OTC pain killers；Hot compress");
        lowerAbdomenbruising.getTherapy().setSelfcareMethods("Hold up the bruised parts");
        lowerAbdomenbruising.getTherapy().setAuxiliaryExamination("x-ray;blood test");
        Symptom lowerAbdomencramps = lowerAbdomen.addSymptom("muscle cramps");
        lowerAbdomencramps.getTherapy().setFirstAidMethods("Interferon；Corticosteroids");
        lowerAbdomencramps.getTherapy().setSelfcareMethods("Take a deep breath or meditate；Use brace, crutches");
        lowerAbdomencramps.getTherapy().setAuxiliaryExamination("Neurological examination；Nuclear magnetic resonance；Spinal cord puncture");
        Symptom lowerAbdomenfever = lowerAbdomen.addSymptom("fever");
        lowerAbdomenfever.getTherapy().setFirstAidMethods("Cut the abscess");
        lowerAbdomenfever.getTherapy().setSelfcareMethods("Use antibacterial soap to clean");
        lowerAbdomenfever.getTherapy().setAuxiliaryExamination("Check the abscess and its surrounding tissue；Wound tissue fluid culture");
        Symptom lowerAbdomendeformity = lowerAbdomen.addSymptom("visible deformity");
        lowerAbdomendeformity.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        lowerAbdomendeformity.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        lowerAbdomendeformity.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");
        Symptom lowerAbdomenbleeding = lowerAbdomen.addSymptom("bleeding");
        lowerAbdomenbleeding.getTherapy().setFirstAidMethods("Extract the excess blood from your ears；Pressure with a bandage to prevent edema");
        lowerAbdomenbleeding.getTherapy().setSelfcareMethods("Cold pack with ice bag；Wear protective headgear");
        lowerAbdomenbleeding.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");

        //arm body part
        BodyPart arm = system.addBodyPart("arm");
        BodyApparatus shoulder = arm.addApparatuses("shoulder");
        Symptom shoulderjoint = shoulder.addSymptom("joint pain");
        shoulderjoint.getTherapy().setFirstAidMethods("DMARD;Inhibit the immune system drugs；Biological agents");
        shoulderjoint.getTherapy().setSelfcareMethods("Anti-inflammatory drugs；Cold compress");
        shoulderjoint.getTherapy().setAuxiliaryExamination("Physical examination；Blood Test;x-ray");
        Symptom shouldernumbness = shoulder.addSymptom("numbness");
        shouldernumbness.getTherapy().setFirstAidMethods("Inject tetanus vaccine");
        shouldernumbness.getTherapy().setSelfcareMethods("Clear chemicals on the skin；Rinse with cold water for 15-20 minutes");
        shouldernumbness.getTherapy().setAuxiliaryExamination("blood test；CT Scan;x-ray");
        Symptom shouldercramps = shoulder.addSymptom("muscle cramps");
        shouldercramps.getTherapy().setFirstAidMethods("Interferon；Corticosteroids");
        shouldercramps.getTherapy().setSelfcareMethods("Take a deep breath or meditate；Use brace, crutches");
        shouldercramps.getTherapy().setAuxiliaryExamination("Neurological examination；Nuclear magnetic resonance；Spinal cord puncture");
        Symptom shoulderstiff = shoulder.addSymptom("stiff");
        shoulderstiff.getTherapy().setFirstAidMethods("Vitamin b12 supplements；Vitamin b12 injection");
        shoulderstiff.getTherapy().setSelfcareMethods("Improve the diet");
        shoulderstiff.getTherapy().setAuxiliaryExamination("blood test；Bone marrow biopsy；Intestinal examination");
        Symptom shoulderdeformity = shoulder.addSymptom("visible deformity");
        shoulderdeformity.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        shoulderdeformity.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        shoulderdeformity.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");
        Symptom shouldermass = shoulder.addSymptom("mass or bulge");
        shouldermass.getTherapy().setFirstAidMethods("Cut the abscess");
        shouldermass.getTherapy().setSelfcareMethods("Use antibacterial soap to clean");
        shouldermass.getTherapy().setAuxiliaryExamination("Check the abscess and its surrounding tissue；Wound tissue fluid culture");
        Symptom shoulderpus = shoulder.addSymptom("drain or pus");
        shoulderpus.getTherapy().setFirstAidMethods("Adrenaline injection；Corticosteroid drugs；Oxygen；Intravenous infusion");
        shoulderpus.getTherapy().setSelfcareMethods("Antihistamines；Ice allergy site");
        shoulderpus.getTherapy().setAuxiliaryExamination("blood test；Allergen test");
        Symptom shoulderbleeding = shoulder.addSymptom("bleeding");
        shoulderbleeding.getTherapy().setFirstAidMethods("Extract the excess blood from your ears；Pressure with a bandage to prevent edema");
        shoulderbleeding.getTherapy().setSelfcareMethods("Cold pack with ice bag；Wear protective headgear");
        shoulderbleeding.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom shoulderbruising = shoulder.addSymptom("bruising discoloration");
        shoulderbruising.getTherapy().setFirstAidMethods("OTC pain killers；Hot compress");
        shoulderbruising.getTherapy().setSelfcareMethods("Hold up the bruised parts");
        shoulderbruising.getTherapy().setAuxiliaryExamination("x-ray;blood test");

        BodyApparatus forearm = arm.addApparatuses("forearm");
        Symptom forearmnumbness = forearm.addSymptom("numbness");
        forearmnumbness.getTherapy().setFirstAidMethods("Inject tetanus vaccine");
        forearmnumbness.getTherapy().setSelfcareMethods("Clear chemicals on the skin；Rinse with cold water for 15-20 minutes");
        forearmnumbness.getTherapy().setAuxiliaryExamination("blood test；CT Scan;x-ray");
        Symptom forearmswelling = forearm.addSymptom("swelling");
        forearmswelling.getTherapy().setFirstAidMethods("Pressure with a bandage to prevent edema；antibiotic");
        forearmswelling.getTherapy().setSelfcareMethods("Cold pack with ice bag");
        forearmswelling.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom forearmpain = forearm.addSymptom("pain or discomfort");
        forearmpain.getTherapy().setFirstAidMethods("Anti-inflammatory drugs；Cortisol injection");
        forearmpain.getTherapy().setSelfcareMethods("Hot compress");
        forearmpain.getTherapy().setAuxiliaryExamination("x-ray；Magnetic resonance imaging；CT scan");
        Symptom forearmdeformity = forearm.addSymptom("visible deformity");
        forearmdeformity.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        forearmdeformity.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        forearmdeformity.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");
        Symptom forearmtenderness = forearm.addSymptom("tenderness");
        forearmtenderness.getTherapy().setFirstAidMethods("Fibromyalgia medication；massage；Stretch regularly；Acupuncture");
        forearmtenderness.getTherapy().setSelfcareMethods("Use heat pads on sore muscles");
        forearmtenderness.getTherapy().setAuxiliaryExamination("x-ray；Magnetic resonance imaging；CT scan");
        Symptom forearmbleeding = forearm.addSymptom("bleeding");
        forearmbleeding.getTherapy().setFirstAidMethods("Extract the excess blood from your ears；Pressure with a bandage to prevent edema");
        forearmbleeding.getTherapy().setSelfcareMethods("Cold pack with ice bag；Wear protective headgear");
        forearmbleeding.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom forearmmass = forearm.addSymptom("mass or bulge");
        forearmmass.getTherapy().setFirstAidMethods("Cut the abscess");
        forearmmass.getTherapy().setSelfcareMethods("Use antibacterial soap to clean");
        forearmmass.getTherapy().setAuxiliaryExamination("Check the abscess and its surrounding tissue；Wound tissue fluid culture");
        Symptom forearmpus = forearm.addSymptom("drain or pus");
        forearmpus.getTherapy().setFirstAidMethods("Adrenaline injection；Corticosteroid drugs；Oxygen；Intravenous infusion");
        forearmpus.getTherapy().setSelfcareMethods("Antihistamines；Ice allergy site");
        forearmpus.getTherapy().setAuxiliaryExamination("blood test；Allergen test");
        Symptom forearmbruising = forearm.addSymptom("bruising discoloration");
        forearmbruising.getTherapy().setFirstAidMethods("OTC pain killers；Hot compress");
        forearmbruising.getTherapy().setSelfcareMethods("Hold up the bruised parts");
        forearmbruising.getTherapy().setAuxiliaryExamination("x-ray;blood test");
        Symptom forearmfracture = forearm.addSymptom("fracture");
        forearmfracture.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        forearmfracture.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        forearmfracture.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");

        BodyApparatus elbow = arm.addApparatuses("elbow");
        Symptom elbownumbness = elbow.addSymptom("numbness");
        elbownumbness.getTherapy().setFirstAidMethods("Inject tetanus vaccine");
        elbownumbness.getTherapy().setSelfcareMethods("Clear chemicals on the skin；Rinse with cold water for 15-20 minutes");
        elbownumbness.getTherapy().setAuxiliaryExamination("blood test；CT Scan;x-ray");
        Symptom elbowtenderness = elbow.addSymptom("tenderness");
        elbowtenderness.getTherapy().setFirstAidMethods("Fibromyalgia medication；massage；Stretch regularly；Acupuncture");
        elbowtenderness.getTherapy().setSelfcareMethods("Use heat pads on sore muscles");
        elbowtenderness.getTherapy().setAuxiliaryExamination("x-ray；Magnetic resonance imaging；CT scan");
        Symptom elbowmass = elbow.addSymptom("mass or bulge");
        elbowmass.getTherapy().setFirstAidMethods("Cut the abscess");
        elbowmass.getTherapy().setSelfcareMethods("Use antibacterial soap to clean");
        elbowmass.getTherapy().setAuxiliaryExamination("Check the abscess and its surrounding tissue；Wound tissue fluid culture");
        Symptom elbowjoint = elbow.addSymptom("joint pain");
        elbowjoint.getTherapy().setFirstAidMethods("DMARD;Inhibit the immune system drugs；Biological agents");
        elbowjoint.getTherapy().setSelfcareMethods("Anti-inflammatory drugs；Cold compress");
        elbowjoint.getTherapy().setAuxiliaryExamination("Physical examination；Blood Test;x-ray");
        Symptom elbowdeformity = elbow.addSymptom("visible deformity");
        elbowdeformity.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        elbowdeformity.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        elbowdeformity.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");
        Symptom elbowbruising = elbow.addSymptom("bruising discoloration");
        elbowbruising.getTherapy().setFirstAidMethods("OTC pain killers；Hot compress");
        elbowbruising.getTherapy().setSelfcareMethods("Hold up the bruised parts");
        elbowbruising.getTherapy().setAuxiliaryExamination("x-ray;blood test");
        Symptom elbowpus = elbow.addSymptom("drain or pus");
        elbowpus.getTherapy().setFirstAidMethods("Adrenaline injection；Corticosteroid drugs；Oxygen；Intravenous infusion");
        elbowpus.getTherapy().setSelfcareMethods("Antihistamines；Ice allergy site");
        elbowpus.getTherapy().setAuxiliaryExamination("blood test；Allergen test");
        Symptom elbowwelling = elbow.addSymptom("swelling");
        elbowwelling.getTherapy().setFirstAidMethods("Pressure with a bandage to prevent edema；antibiotic");
        elbowwelling.getTherapy().setSelfcareMethods("Cold pack with ice bag");
        elbowwelling.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom elbowstiff = elbow.addSymptom("stiff");
        elbowstiff.getTherapy().setFirstAidMethods("Vitamin b12 supplements；Vitamin b12 injection");
        elbowstiff.getTherapy().setSelfcareMethods("Improve the diet");
        elbowstiff.getTherapy().setAuxiliaryExamination("blood test；Bone marrow biopsy；Intestinal examination");
        Symptom elbowbleeding = elbow.addSymptom("bleeding");
        elbowbleeding.getTherapy().setFirstAidMethods("Extract the excess blood from your ears；Pressure with a bandage to prevent edema");
        elbowbleeding.getTherapy().setSelfcareMethods("Cold pack with ice bag；Wear protective headgear");
        elbowbleeding.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom elbowfracture = elbow.addSymptom("fracture");
        elbowfracture.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        elbowfracture.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        elbowfracture.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");

        BodyApparatus wrist = arm.addApparatuses("wrist");
        Symptom wristmass = wrist.addSymptom("mass or bulge");
        wristmass.getTherapy().setFirstAidMethods("Cut the abscess");
        wristmass.getTherapy().setSelfcareMethods("Use antibacterial soap to clean");
        wristmass.getTherapy().setAuxiliaryExamination("Check the abscess and its surrounding tissue；Wound tissue fluid culture");
        Symptom wristswelling = wrist.addSymptom("swelling");
        wristswelling.getTherapy().setFirstAidMethods("Pressure with a bandage to prevent edema；antibiotic");
        wristswelling.getTherapy().setSelfcareMethods("Cold pack with ice bag");
        wristswelling.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom wristbleeding = wrist.addSymptom("bleeding");
        wristbleeding.getTherapy().setFirstAidMethods("Extract the excess blood from your ears；Pressure with a bandage to prevent edema");
        wristbleeding.getTherapy().setSelfcareMethods("Cold pack with ice bag；Wear protective headgear");
        wristbleeding.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom wristnumbness = wrist.addSymptom("numbness");
        wristnumbness.getTherapy().setFirstAidMethods("Inject tetanus vaccine");
        wristnumbness.getTherapy().setSelfcareMethods("Clear chemicals on the skin；Rinse with cold water for 15-20 minutes");
        wristnumbness.getTherapy().setAuxiliaryExamination("blood test；CT Scan;x-ray");
        Symptom wristdeformity = wrist.addSymptom("visible deformity");
        wristdeformity.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        wristdeformity.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        wristdeformity.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");
        Symptom wristfracture = wrist.addSymptom("fracture");
        wristfracture.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        wristfracture.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        wristfracture.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");
        Symptom wriststiff = wrist.addSymptom("stiff");
        wriststiff.getTherapy().setFirstAidMethods("Vitamin b12 supplements；Vitamin b12 injection");
        wriststiff.getTherapy().setSelfcareMethods("Improve the diet");
        wriststiff.getTherapy().setAuxiliaryExamination("blood test；Bone marrow biopsy；Intestinal examination");
        Symptom wristpus = wrist.addSymptom("drain or pus");
        wristpus.getTherapy().setFirstAidMethods("Adrenaline injection；Corticosteroid drugs；Oxygen；Intravenous infusion");
        wristpus.getTherapy().setSelfcareMethods("Antihistamines；Ice allergy site");
        wristpus.getTherapy().setAuxiliaryExamination("blood test；Allergen test");

        BodyApparatus finger = arm.addApparatuses("finger");
        Symptom fingernumbness = finger.addSymptom("numbness");
        fingernumbness.getTherapy().setFirstAidMethods("Inject tetanus vaccine");
        fingernumbness.getTherapy().setSelfcareMethods("Clear chemicals on the skin；Rinse with cold water for 15-20 minutes");
        fingernumbness.getTherapy().setAuxiliaryExamination("blood test；CT Scan;x-ray");
        Symptom fingerstiff = finger.addSymptom("stiff");
        fingerstiff.getTherapy().setFirstAidMethods("Vitamin b12 supplements；Vitamin b12 injection");
        fingerstiff.getTherapy().setSelfcareMethods("Improve the diet");
        fingerstiff.getTherapy().setAuxiliaryExamination("blood test；Bone marrow biopsy；Intestinal examination");
        Symptom fingerswelling = finger.addSymptom("swelling");
        fingerswelling.getTherapy().setFirstAidMethods("Pressure with a bandage to prevent edema；antibiotic");
        fingerswelling.getTherapy().setSelfcareMethods("Cold pack with ice bag");
        fingerswelling.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom fingerbleeding = finger.addSymptom("bleeding");
        fingerbleeding.getTherapy().setFirstAidMethods("Extract the excess blood from your ears；Pressure with a bandage to prevent edema");
        fingerbleeding.getTherapy().setSelfcareMethods("Cold pack with ice bag；Wear protective headgear");
        fingerbleeding.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom fingerbruising = finger.addSymptom("bruising discoloration");
        fingerbruising.getTherapy().setFirstAidMethods("OTC pain killers；Hot compress");
        fingerbruising.getTherapy().setSelfcareMethods("Hold up the bruised parts");
        fingerbruising.getTherapy().setAuxiliaryExamination("x-ray;blood test");
        Symptom fingerdeformity = finger.addSymptom("visible deformity");
        fingerdeformity.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        fingerdeformity.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        fingerdeformity.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");
        Symptom fingercramps = finger.addSymptom("muscle cramps");
        fingercramps.getTherapy().setFirstAidMethods("Interferon；Corticosteroids");
        fingercramps.getTherapy().setSelfcareMethods("Take a deep breath or meditate；Use brace, crutches");
        fingercramps.getTherapy().setAuxiliaryExamination("Neurological examination；Nuclear magnetic resonance；Spinal cord puncture");
        Symptom fingerpus = finger.addSymptom("drain or pus");
        fingerpus.getTherapy().setFirstAidMethods("Adrenaline injection；Corticosteroid drugs；Oxygen；Intravenous infusion");
        fingerpus.getTherapy().setSelfcareMethods("Antihistamines；Ice allergy site");
        fingerpus.getTherapy().setAuxiliaryExamination("blood test；Allergen test");
        Symptom fingerfracture = finger.addSymptom("fracture");
        fingerfracture.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        fingerfracture.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        fingerfracture.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");

        //leg body part
        BodyPart leg = system.addBodyPart("leg");
        BodyApparatus thigh = leg.addApparatuses("thigh");
        Symptom thighpain = thigh.addSymptom("pain or discomfort");
        thighpain.getTherapy().setFirstAidMethods("Anti-inflammatory drugs；Cortisol injection");
        thighpain.getTherapy().setSelfcareMethods("Hot compress");
        thighpain.getTherapy().setAuxiliaryExamination("x-ray；Magnetic resonance imaging；CT scan");
        Symptom thighswelling = thigh.addSymptom("swelling");
        thighswelling.getTherapy().setFirstAidMethods("Pressure with a bandage to prevent edema；antibiotic");
        thighswelling.getTherapy().setSelfcareMethods("Cold pack with ice bag");
        thighswelling.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom thighnumbness = thigh.addSymptom("numbness");
        thighnumbness.getTherapy().setFirstAidMethods("Inject tetanus vaccine");
        thighnumbness.getTherapy().setSelfcareMethods("Clear chemicals on the skin；Rinse with cold water for 15-20 minutes");
        thighnumbness.getTherapy().setAuxiliaryExamination("blood test；CT Scan;x-ray");
        Symptom thighcramps = thigh.addSymptom("muscle cramps");
        thighcramps.getTherapy().setFirstAidMethods("Interferon；Corticosteroids");
        thighcramps.getTherapy().setSelfcareMethods("Take a deep breath or meditate；Use brace, crutches");
        thighcramps.getTherapy().setAuxiliaryExamination("Neurological examination；Nuclear magnetic resonance；Spinal cord puncture");
        Symptom thighmass = thigh.addSymptom("mass or bulge");
        thighmass.getTherapy().setFirstAidMethods("Cut the abscess");
        thighmass.getTherapy().setSelfcareMethods("Use antibacterial soap to clean");
        thighmass.getTherapy().setAuxiliaryExamination("Check the abscess and its surrounding tissue；Wound tissue fluid culture");
        Symptom thighveins = thigh.addSymptom("varicose veins");
        blindness.getTherapy().setFirstAidMethods("");
        blindness.getTherapy().setSelfcareMethods("");
        blindness.getTherapy().setAuxiliaryExamination("");
        Symptom thighdeformity = thigh.addSymptom("visible deformity");
        thighdeformity.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        thighdeformity.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        thighdeformity.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");
        Symptom thighfracture = thigh.addSymptom("fracture");
        thighfracture.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        thighfracture.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        thighfracture.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");
        Symptom thighbruising = thigh.addSymptom("bruising discoloration");
        thighbruising.getTherapy().setFirstAidMethods("OTC pain killers；Hot compress");
        thighbruising.getTherapy().setSelfcareMethods("Hold up the bruised parts");
        thighbruising.getTherapy().setAuxiliaryExamination("x-ray;blood test");
        Symptom thighpus = thigh.addSymptom("drain or pus");
        thighpus.getTherapy().setFirstAidMethods("Adrenaline injection；Corticosteroid drugs；Oxygen；Intravenous infusion");
        thighpus.getTherapy().setSelfcareMethods("Antihistamines；Ice allergy site");
        thighpus.getTherapy().setAuxiliaryExamination("blood test；Allergen test");
        Symptom thighbleeding = thigh.addSymptom("bleeding");
        thighbleeding.getTherapy().setFirstAidMethods("Extract the excess blood from your ears；Pressure with a bandage to prevent edema");
        thighbleeding.getTherapy().setSelfcareMethods("Cold pack with ice bag；Wear protective headgear");
        thighbleeding.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");

        BodyApparatus knee = leg.addApparatuses("knee");
        Symptom kneejoint = knee.addSymptom("joint pain");
        kneejoint.getTherapy().setFirstAidMethods("DMARD;Inhibit the immune system drugs；Biological agents");
        kneejoint.getTherapy().setSelfcareMethods("Anti-inflammatory drugs；Cold compress");
        kneejoint.getTherapy().setAuxiliaryExamination("Physical examination；Blood Test;x-ray");
        Symptom kneeswelling = knee.addSymptom("swelling");
        kneeswelling.getTherapy().setFirstAidMethods("Pressure with a bandage to prevent edema；antibiotic");
        kneeswelling.getTherapy().setSelfcareMethods("Cold pack with ice bag");
        kneeswelling.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom kneenumbness = knee.addSymptom("numbness");
        kneenumbness.getTherapy().setFirstAidMethods("Inject tetanus vaccine");
        kneenumbness.getTherapy().setSelfcareMethods("Clear chemicals on the skin；Rinse with cold water for 15-20 minutes");
        kneenumbness.getTherapy().setAuxiliaryExamination("blood test；CT Scan;x-ray");
        Symptom kneemass = knee.addSymptom("mass or bulge");
        kneemass.getTherapy().setFirstAidMethods("Cut the abscess");
        kneemass.getTherapy().setSelfcareMethods("Use antibacterial soap to clean");
        kneemass.getTherapy().setAuxiliaryExamination("Check the abscess and its surrounding tissue；Wound tissue fluid culture");
        Symptom kneeveins = knee.addSymptom("varicose veins");
        kneeveins.getTherapy().setFirstAidMethods("");
        kneeveins.getTherapy().setSelfcareMethods("");
        kneeveins.getTherapy().setAuxiliaryExamination("");
        Symptom kneedeformity = knee.addSymptom("visible deformity");
        kneedeformity.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        kneedeformity.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        kneedeformity.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");
        Symptom kneebruising = knee.addSymptom("bruising discoloration");
        kneebruising.getTherapy().setFirstAidMethods("OTC pain killers；Hot compress");
        kneebruising.getTherapy().setSelfcareMethods("Hold up the bruised parts");
        kneebruising.getTherapy().setAuxiliaryExamination("x-ray;blood test");
        Symptom kneedrain = knee.addSymptom("drain or pus");
        kneedrain.getTherapy().setFirstAidMethods("Adrenaline injection；Corticosteroid drugs；Oxygen；Intravenous infusion");
        kneedrain.getTherapy().setSelfcareMethods("Antihistamines；Ice allergy site");
        kneedrain.getTherapy().setAuxiliaryExamination("blood test；Allergen test");

        BodyApparatus calf = leg.addApparatuses("calf");
        Symptom calfpain = calf.addSymptom("pain or discomfort");
        calfpain.getTherapy().setFirstAidMethods("Anti-inflammatory drugs；Cortisol injection");
        calfpain.getTherapy().setSelfcareMethods("Hot compress");
        calfpain.getTherapy().setAuxiliaryExamination("x-ray；Magnetic resonance imaging；CT scan");
        Symptom calfpowerless = calf.addSymptom("powerless");
        calfpowerless.getTherapy().setFirstAidMethods("");
        calfpowerless.getTherapy().setSelfcareMethods("");
        calfpowerless.getTherapy().setAuxiliaryExamination("");
        Symptom calfswelling = calf.addSymptom("swelling");
        calfswelling.getTherapy().setFirstAidMethods("Pressure with a bandage to prevent edema；antibiotic");
        calfswelling.getTherapy().setSelfcareMethods("Cold pack with ice bag");
        calfswelling.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");
        Symptom calfnumbness = calf.addSymptom("numbness");
        calfnumbness.getTherapy().setFirstAidMethods("Inject tetanus vaccine");
        calfnumbness.getTherapy().setSelfcareMethods("Clear chemicals on the skin；Rinse with cold water for 15-20 minutes");
        calfnumbness.getTherapy().setAuxiliaryExamination("blood test；CT Scan;x-ray ");
        Symptom calfcramps = calf.addSymptom("muscle cramps");
        calfcramps.getTherapy().setFirstAidMethods("Interferon；Corticosteroids");
        calfcramps.getTherapy().setSelfcareMethods("Take a deep breath or meditate；Use brace, crutches");
        calfcramps.getTherapy().setAuxiliaryExamination("Neurological examination；Nuclear magnetic resonance；Spinal cord puncture");
        Symptom calfmass = calf.addSymptom("mass or bulge");
        calfmass.getTherapy().setFirstAidMethods("");
        calfmass.getTherapy().setSelfcareMethods("");
        calfmass.getTherapy().setAuxiliaryExamination("");
        Symptom calfveins = calf.addSymptom("varicose veins");
        calfveins.getTherapy().setFirstAidMethods("");
        calfveins.getTherapy().setSelfcareMethods("");
        calfveins.getTherapy().setAuxiliaryExamination("");
        Symptom calfdeformity = calf.addSymptom("visible deformity");
        calfdeformity.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        calfdeformity.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        calfdeformity.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");
        Symptom calffracture = calf.addSymptom("fracture");
        calffracture.getTherapy().setFirstAidMethods("Narcotic or over-the-counter painkiller；Oxygen；Surgical repair of fractures");
        calffracture.getTherapy().setSelfcareMethods("Cold compress；OTC pain killers");
        calffracture.getTherapy().setAuxiliaryExamination("X-ray;CT Scan；blood test；Ultrasound examination；Electrocardiogram");
        Symptom calfdiscoloration = calf.addSymptom("bruising discoloration");
        calfdiscoloration.getTherapy().setFirstAidMethods("OTC pain killers；Hot compress");
        calfdiscoloration.getTherapy().setSelfcareMethods("Hold up the bruised parts");
        calfdiscoloration.getTherapy().setAuxiliaryExamination("x-ray;blood test");
        Symptom calfdrain = calf.addSymptom("drain or pus");
        calfdrain.getTherapy().setFirstAidMethods("Adrenaline injection；Corticosteroid drugs；Oxygen；Intravenous infusion");
        calfdrain.getTherapy().setSelfcareMethods("Antihistamines；Ice allergy site");
        calfdrain.getTherapy().setAuxiliaryExamination("blood test；Allergen test");
        Symptom calfbleeding = calf.addSymptom("bleeding");
        calfbleeding.getTherapy().setFirstAidMethods("Extract the excess blood from your ears；Pressure with a bandage to prevent edema");
        calfbleeding.getTherapy().setSelfcareMethods("Cold pack with ice bag；Wear protective headgear");
        calfbleeding.getTherapy().setAuxiliaryExamination("CT Scan;Magnetic resonance imaging");

        //add medicine
        Medicine Abacavir = system.getMedicineCatalog().addMedicine("Abacavir");
        Abacavir.setDescription("a complex glycoprotein and polysaccharide mixture , and in the past, arabinose or ribose and other substances are also named after the gum arabic separation. The structure is a mixture of saccharides , potassium , magnesium and calcium which are connected through branches , and the monomer structure of the composition includes galactose , arabinose, rhamnose and glucuronic acid");
        Medicine Aluminum = system.getMedicineCatalog().addMedicine("Aluminum Sulfate");
        Aluminum.setDescription("a complex glycoprotein and polysaccharide mixture , and in the past, arabinose or ribose and other substances are also named after the gum arabic separation. The structure is a mixture of saccharides , potassium , magnesium and calcium which are connected through branches , and the monomer structure of the composition includes galactose , arabinose, rhamnose and glucuronic acid");
        Medicine Bacitracin = system.getMedicineCatalog().addMedicine("Bacitracin");
        Bacitracin.setDescription("a complex glycoprotein and polysaccharide mixture , and in the past, arabinose or ribose and other substances are also named after the gum arabic separation. The structure is a mixture of saccharides , potassium , magnesium and calcium which are connected through branches , and the monomer structure of the composition includes galactose , arabinose, rhamnose and glucuronic acid");
        Medicine Cefazolin = system.getMedicineCatalog().addMedicine("Cefazolin");
        Cefazolin.setDescription("a complex glycoprotein and polysaccharide mixture , and in the past, arabinose or ribose and other substances are also named after the gum arabic separation. The structure is a mixture of saccharides , potassium , magnesium and calcium which are connected through branches , and the monomer structure of the composition includes galactose , arabinose, rhamnose and glucuronic acid");
        Medicine Doxycycline = system.getMedicineCatalog().addMedicine("Doxycycline");
        Doxycycline.setDescription("a complex glycoprotein and polysaccharide mixture , and in the past, arabinose or ribose and other substances are also named after the gum arabic separation. The structure is a mixture of saccharides , potassium , magnesium and calcium which are connected through branches , and the monomer structure of the composition includes galactose , arabinose, rhamnose and glucuronic acid");
        Medicine Erythromycin = system.getMedicineCatalog().addMedicine("Erythromycin");
        Erythromycin.setDescription("a complex glycoprotein and polysaccharide mixture , and in the past, arabinose or ribose and other substances are also named after the gum arabic separation. The structure is a mixture of saccharides , potassium , magnesium and calcium which are connected through branches , and the monomer structure of the composition includes galactose , arabinose, rhamnose and glucuronic acid");
        Medicine Fosfomycin = system.getMedicineCatalog().addMedicine("Fosfomycin");
        Fosfomycin.setDescription("a complex glycoprotein and polysaccharide mixture , and in the past, arabinose or ribose and other substances are also named after the gum arabic separation. The structure is a mixture of saccharides , potassium , magnesium and calcium which are connected through branches , and the monomer structure of the composition includes galactose , arabinose, rhamnose and glucuronic acid");

        return system;
    }

}
