/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.EMSWorkArea;

import Business.Ambulance.Ambulance;
import Business.Ambulance.AmbulanceService;
import Business.Enterprise.EMSEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Role.FirstAiderRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SOSRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xingyaowu
 */
public class EMSConductingAmbJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private SOSRequest request;

    public EMSConductingAmbJPanel(JPanel userProcessContainer, Enterprise enterprise, SOSRequest request) {
        initComponents();
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        table.setRowSelectionAllowed(true);
        table.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        patientNameTextField.setText(request.getName());
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        requestDateTextField.setText(dt.format(request.getRequestDate()));
        if (request.getAmbulanceService() != null) {
            ambulanceTextField.setText(request.getAmbulanceService().getAmbulance().getName());
        }
        statusTextField.setText(request.getStatus());
        populateList();
        populateTable();
    }

    private void populateList() {
        DefaultListModel listModel = new DefaultListModel();
        EMSEnterprise eMSEnterprise = (EMSEnterprise) enterprise;
        for (Ambulance amb : eMSEnterprise.getAmbulances()) {
            if (amb.getStatus().equals("Free")) {
                listModel.addElement(amb);
            }
        }
        ambList.setModel(listModel);
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount account : org.getUserAccountDirectory().getUserAccountList()) {
                if (account.getRole() instanceof FirstAiderRole && account.getStatus().equals("Available")) {
                    Object row[] = new Object[1];
                    row[0] = account;
                    model.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ambulanceTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        statusTextField = new javax.swing.JTextField();
        patientNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        requestDateTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ambList = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        assignBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        viewMapBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("EMS Conducting Service");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 6, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 622, -1));

        ambulanceTextField.setEnabled(false);
        add(ambulanceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 70, 171, -1));

        jLabel5.setText("Current Status:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 113, -1, -1));

        statusTextField.setEnabled(false);
        statusTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTextFieldActionPerformed(evt);
            }
        });
        add(statusTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 108, 171, -1));

        patientNameTextField.setEnabled(false);
        add(patientNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 108, 161, -1));

        jLabel2.setText("Patient Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 70, -1, -1));

        jLabel3.setText("Request Date:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 113, -1, -1));

        requestDateTextField.setEnabled(false);
        add(requestDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 70, 161, -1));

        jLabel4.setText("Ambulance Assigned:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 75, -1, -1));

        jScrollPane1.setViewportView(ambList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 213));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Available Ambulance：");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Available First Aider：");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 140, -1, -1));

        assignBtn.setText("Assign");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });
        add(assignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 407, -1, -1));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 407, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aider Name:"
            }
        ));
        jScrollPane2.setViewportView(table);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 322, 213));

        viewMapBtn.setText("Locate");
        viewMapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMapBtnActionPerformed(evt);
            }
        });
        add(viewMapBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 407, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void statusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTextFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        int[] selectedRow = table.getSelectedRows();
        if (selectedRow.length > 0) {
            Ambulance amb = (Ambulance) ambList.getSelectedValue();
            if (amb == null) {
                JOptionPane.showMessageDialog(null, "Please select an ambluance.");
            } else {
                amb.setStatus("On duty");
                AmbulanceService service = new AmbulanceService(amb);
                for (int eachRow : selectedRow) {
                    UserAccount aider = (UserAccount) table.getValueAt(eachRow, 0);
                    aider.setStatus("Unavailable");
                    service.getListOfAiders().add(aider);
                }
                request.setAmbulanceService(service);
                ambulanceTextField.setText(amb.getName());
                request.setStatus("EMS Ready");
            }
        }
    }//GEN-LAST:event_assignBtnActionPerformed

    private void viewMapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMapBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewMapBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ambList;
    private javax.swing.JTextField ambulanceTextField;
    private javax.swing.JButton assignBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField patientNameTextField;
    private javax.swing.JTextField requestDateTextField;
    private javax.swing.JTextField statusTextField;
    private javax.swing.JTable table;
    private javax.swing.JButton viewMapBtn;
    // End of variables declaration//GEN-END:variables
}
